@bookingUrl = {{$dotenv BOOKING_URL}}
@authToken = {{$dotenv JWT_TOKEN}}


### Register
POST {{bookingUrl}}/auth/register
Content-Type: application/json

{
  "email": "example@mail.ru",
  "password": "34h2hhVFhSHFHbB@Bfus"
}

### Login
POST {{bookingUrl}}/auth/login
Content-Type: application/json

{
  "email": "example@mail.ru",
  "password": "34h2hhVFhSHFHbB@Bfus"
}


### Get charging stations
@offset = 0
@limit = 20

GET {{bookingUrl}}/stations?offset={{offset}}&limit={{limit}}
Content-Type: application/json


### Get charging station by id
@id = 6f793b9a-4c93-4b76-99a1-7d197f25c195

GET {{bookingUrl}}/stations/{{id}}
Content-Type: application/json


### Create charging station
POST {{bookingUrl}}/stations
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Tesla Supercharger Berlin",
  "address": "Alexanderplatz 1, Berlin",
  "latitude": 52.5200,
  "longitude": 13.4050
}


### Update charging station
@stationID = 6f793b9a-4c93-4b76-99a1-7d197f25c195

PUT {{bookingUrl}}/stations/{{stationID}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Tesla Supercharger Berlin Updated",
  "address": "Alexanderplatz 5, Berlin",
  "latitude": 52.5208,
  "longitude": 13.4095
}


### Delete charging station
DELETE {{bookingUrl}}/stations/{{stationID}}
Authorization: Bearer {{authToken}}