@bookingUrl = {{$dotenv BOOKING_URL}}
@authToken = {{$dotenv JWT_TOKEN}}


### Register
POST {{bookingUrl}}/auth/register
Content-Type: application/json

{
  "email": "{{$dotenv TEST_USER_EMAIL}}",
  "password": "{{$dotenv TEST_USER_PASSWORD}}"
}

### Login
POST {{bookingUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{$dotenv TEST_USER_EMAIL}}",
  "password": "{{$dotenv TEST_USER_PASSWORD}}"
}

### Admin Login
POST {{bookingUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{$dotenv ADMIN_EMAIL}}",
  "password": "{{$dotenv ADMIN_PASSWORD}}"
}


### Get charging stations
@offset = 0
@limit = 20

GET {{bookingUrl}}/stations?offset={{offset}}&limit={{limit}}
Content-Type: application/json


### Get charging station by id
@stationID = 8a078fc4-853e-4108-b2a5-4ddd6df55f26

GET {{bookingUrl}}/stations/{{stationID}}
Content-Type: application/json


### Create charging station
POST {{bookingUrl}}/stations
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Tesla Supercharger Berlin",
  "address": "Alexanderplatz 1, Berlin",
  "latitude": 52.5200,
  "longitude": 13.4050
}


### Update charging station

PUT {{bookingUrl}}/stations/{{stationID}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Tesla Supercharger Berlin Updated",
  "address": "Alexanderplatz 5, Berlin",
  "latitude": 52.5208,
  "longitude": 13.4095
}


### Delete charging station
DELETE {{bookingUrl}}/stations/{{stationID}}
Authorization: Bearer {{authToken}}


### Get charging ports by station
GET {{bookingUrl}}/stations/{{stationID}}/ports
Content-Type: application/json