@bookingUrl = http://localhost:8080

### Register
POST {{bookingUrl}}/auth/register
Content-Type: application/json

{
  "email": "example@mail.ru",
  "password": "34h2hhVFhSHFHbB@Bfus"
}

### Login
POST {{bookingUrl}}/auth/login
Content-Type: application/json

{
  "email": "example@mail.ru",
  "password": "34h2hhVFhSHFHbB@Bfus"
}