services:
  # AUTH 
  auth-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${AUTH_REPOSITORY_USER}
      POSTGRES_PASSWORD: ${AUTH_REPOSITORY_PASSWORD}
      POSTGRES_DB: ${AUTH_REPOSITORY_NAME}
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_REPOSITORY_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-migrate:
    image: migrate/migrate
    depends_on:
      auth-db:
        condition: service_healthy

    volumes:
      - ../../services/auth/migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://${AUTH_REPOSITORY_USER}:${AUTH_REPOSITORY_PASSWORD}@${AUTH_REPOSITORY_HOST}:${AUTH_REPOSITORY_PORT}/${AUTH_REPOSITORY_NAME}?sslmode=${AUTH_REPOSITORY_SSLMODE}",
        "up"
      ]
    restart: "no"
    environment:
      AUTH_REPOSITORY_USER: ${AUTH_REPOSITORY_USER}
      AUTH_REPOSITORY_PASSWORD: ${AUTH_REPOSITORY_PASSWORD}
      AUTH_REPOSITORY_PORT: ${AUTH_REPOSITORY_PORT}
      AUTH_REPOSITORY_HOST: ${AUTH_REPOSITORY_HOST}
      AUTH_REPOSITORY_NAME: ${AUTH_REPOSITORY_NAME}
      AUTH_REPOSITORY_SSLMODE: ${AUTH_REPOSITORY_SSLMODE}
    
  auth-seed-admin:
    build:
      context: ../../
      dockerfile: services/auth/Dockerfile

    command: ["./seed-admin"]

    depends_on:
      auth-migrate:
        condition: service_completed_successfully
    environment:
      AUTH_CONFIG_PATH: ${AUTH_CONFIG_PATH}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      AUTH_REPOSITORY_USER: ${AUTH_REPOSITORY_USER}
      AUTH_REPOSITORY_PASSWORD: ${AUTH_REPOSITORY_PASSWORD}
      AUTH_REPOSITORY_PORT: ${AUTH_REPOSITORY_PORT}
      AUTH_REPOSITORY_HOST: ${AUTH_REPOSITORY_HOST}
      AUTH_REPOSITORY_NAME: ${AUTH_REPOSITORY_NAME}
      AUTH_REPOSITORY_SSLMODE: ${AUTH_REPOSITORY_SSLMODE}
    volumes:
    - ../../services/auth/config:/app/config

  auth-service:
    build: 
      context: ../../
      dockerfile: services/auth/Dockerfile
    ports:
      - "44044:44044"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:44044"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    depends_on:
      auth-db:
        condition: service_healthy
      auth-migrate:
        condition: service_completed_successfully
      auth-seed-admin:
        condition: service_completed_successfully
    environment:
      AUTH_CONFIG_PATH: ${AUTH_CONFIG_PATH}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: ${JWT_TTL}
      AUTH_REPOSITORY_USER: ${AUTH_REPOSITORY_USER}
      AUTH_REPOSITORY_PASSWORD: ${AUTH_REPOSITORY_PASSWORD}
      AUTH_REPOSITORY_PORT: ${AUTH_REPOSITORY_PORT}
      AUTH_REPOSITORY_HOST: ${AUTH_REPOSITORY_HOST}
      AUTH_REPOSITORY_NAME: ${AUTH_REPOSITORY_NAME}
      AUTH_REPOSITORY_SSLMODE: ${AUTH_REPOSITORY_SSLMODE}
    volumes:
      - ../../services/auth/config:/app/config

  # BOOKING
  booking-db:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: ${BOOKING_REPOSITORY_USER}
      POSTGRES_PASSWORD: ${BOOKING_REPOSITORY_PASSWORD}
      POSTGRES_DB: ${BOOKING_REPOSITORY_NAME}
    ports:
      - "5433:5432"
    volumes:
      - booking_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BOOKING_REPOSITORY_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  booking-migrate:
    image: migrate/migrate
    depends_on:
      booking-db:
        condition: service_healthy
    volumes:
      - ../../services/booking/migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://${BOOKING_REPOSITORY_USER}:${BOOKING_REPOSITORY_PASSWORD}@${BOOKING_REPOSITORY_HOST}:${BOOKING_REPOSITORY_PORT}/${BOOKING_REPOSITORY_NAME}?sslmode=${BOOKING_REPOSITORY_SSLMODE}",
        "up"
      ]
    restart: "no"
    environment:
      BOOKING_REPOSITORY_USER: ${BOOKING_REPOSITORY_USER}
      BOOKING_REPOSITORY_PASSWORD: ${BOOKING_REPOSITORY_PASSWORD}
      BOOKING_REPOSITORY_PORT: ${BOOKING_REPOSITORY_PORT}
      BOOKING_REPOSITORY_HOST: ${BOOKING_REPOSITORY_HOST}
      BOOKING_REPOSITORY_NAME: ${BOOKING_REPOSITORY_NAME}
      BOOKING_REPOSITORY_SSLMODE: ${BOOKING_REPOSITORY_SSLMODE}

  booking-service:
    build:
      context: ../../
      dockerfile: services/booking/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      booking-db:
        condition: service_healthy
      booking-migrate:
        condition: service_completed_successfully
      auth-service:
        condition: service_healthy
    
    environment:
      BOOKING_CONFIG_PATH: ${BOOKING_CONFIG_PATH}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: ${JWT_TTL}
      BOOKING_REPOSITORY_USER: ${BOOKING_REPOSITORY_USER}
      BOOKING_REPOSITORY_PASSWORD: ${BOOKING_REPOSITORY_PASSWORD}
      BOOKING_REPOSITORY_PORT: ${BOOKING_REPOSITORY_PORT}
      BOOKING_REPOSITORY_HOST: ${BOOKING_REPOSITORY_HOST}
      BOOKING_REPOSITORY_NAME: ${BOOKING_REPOSITORY_NAME}
      BOOKING_REPOSITORY_SSLMODE: ${BOOKING_REPOSITORY_SSLMODE}
    volumes:
      - ../../services/booking/config:/app/config
volumes:
  auth_pgdata:
  booking_pgdata: